name: easy_native
description: "A powerful Flutter plugin for seamless native routing management and bidirectional communication between Flutter and iOS/Android."
version: 0.0.2
homepage: https://github.com/MengLiMing/easy_native
repository: https://github.com/MengLiMing/easy_native
environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.easy_native
        pluginClass: EasyNativePlugin
      ios:
        pluginClass: EasyNativePlugin
